### ISSUE TITLE
Wrong string value when enum has no other attributes

### ISSUE THREAD

**Issue by matdurand** [zarldev/goenums#24]
Hey, me again.

I got a little bug here.

Starting from the planet example, I'm trying to only customize the enum string value. If I remove all the attributes and just try to provide an string value, like this:
```
type planet int

//go:generate goenums planet.go
const (
	unknown planet = iota // invalid
	mercury               // Mercury
	venus                 // Venus
	earth                 // Earth
	mars                  // Mars
	jupiter               // Jupiter
	saturn                // Saturn
	uranus                // Uranus
	neptune               // Neptune
)
```

the generated names are all lower case, ignoring the provided value
```
const _planets_name = "unknownmercuryvenusearthmarsjupitersaturnuranusneptune"
```

As soon as I have one attribute, I get the capitalized string values.

**Comment by zarldev** [comment]
Fixed in v0.3.1

**Comment by matdurand** [comment]
Should the `stringToXXX` method also use these provided custom values to parse instead of the regular? And since it's doing a `ToLower` on the value, what happens if I provide CAPS values. It would need to lowercase the values in the switch statement as well. I'm wondering if the `ToLower` should be driven by an generator option as this might not be desirable in all cases (but that's not the purpose of this issue).

Finally, the `.String()` method doesn't seem to work (at least I think it doesn't, unless I'm doing something wrong).
```
fmt.Println(domain.DiscountTypes.PERCENTAGE.String())
```
output empty string.

**Comment by zarldev** [comment]
Fixed in v0.3.2 There should be no need for a generator flag - code should handle this correctly now. Removed two lower and work with spacing and values defined.

**Comment by matdurand** [comment]
Not quite fixed yet. 

With the following definition (without the unknown value)
```
type discountType int
const (
	percentage discountType = iota + 1 //doing +1 here because I assume we wanna stay away from the zero value if there is no invalid value
	amount
	giveaway
)
```
if I output a value, it outputs the wrong value
```
fmt.Println(domain.DiscountTypes.PERCENTAGE.String()) //outputs "amount" instead of percentage.
```

Is it allowed to not have the unknown value in the definition? If not, then something should fail at generation time.

**Comment by zarldev** [comment]
This is a smaller bug for non 0 indexed iota and works correctly with 0 indexed iotas.  
I'm going to write more exhaustive test suite.  You do not need to have a unknown type or worry about 0 indexed.   I moved from using the index for this calculation and is an oversight.

**Comment by zarldev** [comment]
@matdurand I have added test cases for the string representations - if you are still having any issues please let me know - 

This should be fixed in v0.3.4

**Comment by matdurand** [comment]
LGTM! thanks

**Comment by matdurand** [comment]
Spoke too soon :|

**Comment by matdurand** [comment]
Am I correct in saying that if I pass an int to Parse, then it should respect the iota values? so if I do this
```
//go:generate go run github.com/zarldev/goenums -f discounttypes.go
type discountType int

const (
	percentage discountType = iota + 1
	amount                             
	giveaway                          
)
```
then `ParseDiscountType(1)` should return `Percentage`? Right now it returns `Amount`.

**Comment by matdurand** [comment]
Another minor thing, and I feel like I'm getting way off topic with the original issue, but maybe we could change the message
in Parse
```
return res, fmt.Errorf("failed to parse %v", a)
```
to include the enum name? like "failed to parse DiscountType: %v"? Otherwise, it's kind of hard to know where the error is coming from.

**Comment by zarldev** [comment]
I have extended the Error message to be more descriptive and I have also set the index offset for when you are using the ParseXXX with an int input.  Thanks for the help on this @matdurand

**Comment by zarldev** [comment]
@matdurand I will close this issue soon if no more feedback.  Thanks

**Comment by matdurand** [comment]
Sorry, I forgot to comment, but it works, closing it now!
